apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
        - name: notes-backend
          image: ghcr.io/goofy-56/notes-backend:latest
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: notes-backend
spec:
  type: ClusterIP
  selector:
    app: notes-backend
  ports:
    - port: 4000
      targetPort: 4000
