apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-frontend
  template:
    metadata:
      labels:
        app: notes-frontend
    spec:
      containers:
        - name: notes-frontend
          image: ghcr.io/goofy-56/notes-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: notes-frontend
spec:
  type: NodePort
  selector:
    app: notes-frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
