name: Build and Push Docker Images to GHCR
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: goofy-56
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Frontend
        run: |
          docker build -t ghcr.io/goofy-56/notes-frontend:latest ./frontend
          docker push ghcr.io/goofy-56/notes-frontend:latest
      - name: Build and Push Backend
        run: |
          docker build -t ghcr.io/goofy-56/notes-backend:latest ./backend
          docker push ghcr.io/goofy-56/notes-backend:latest
